services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ebarokah-app
    container_name: ebarokah_app
    ports:
      - "1025:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    networks:
      - ebarokahnet

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: ebarokah_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ebarokah
      MYSQL_USER: ebarokah_user
      MYSQL_PASSWORD: ebarokah25
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - ebarokahnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "11255:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./upload.ini:/usr/local/etc/php/conf.d/upload.ini
      - ./sessions:/sessions
    networks:
      - ebarokahnet

  db-backup:
    image: mysql:5.7
    platform: linux/amd64
    container_name: ebarokah_db_backup
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./db_backups:/backup
    entrypoint: >
      sh -c "apt-get update && apt-get install -y cron mysql-client &&
            echo '0 2 * * * mysqldump -h db -u${MYSQL_USER} -p${MYSQL_PASSWORD} ${MYSQL_DATABASE} > /backup/db_backup_$(date +\%Y\%m\%d_\%H\%M\%S).sql' > /etc/crontab &&
            cron -f"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  db_data:

networks:
  ebarokahnet:
